# Basic config
baseURL = "https://petermiller310.github.io/"
theme = "hugo-simple"
languageCode = "en-US"
title = "peter's blog"
enableRobotsTXT = true
capitalizeListTitles = false

# Taxonomy settings
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

# Markup settings
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 3

[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

# Parameters
[params]
title = "peter's blog"
description = "personal blog"
dateFormat = "2006-01-02"
hideMadeWithLine = true
hideRSSLink = true
github = "petermiller310"
favicon = "images/favicon.png"

# Author information
[params.author]
name = "peter's blog"
email = ""

# Navigation menu
[[menu.main]]
name = "home"
pageRef = "/"
weight = 10

[[menu.main]]
name = "blog"
pageRef = "/posts"
weight = 20

# Pagination
[pagination]
pagerSize = 16

# Output formats
[outputs]
home = ["html"]
section = ["html"]
taxonomy = ["html"]
term = ["html"]
